graphName: "biochemical_network"
schema: "biochemical_network.gql"
scales:
  - 500
  - 1000
  - 2000
repeatsPerQuery: 5

queries: "queries.yml"
deleteInsertedConcepts: true

concurrency:
  clients: 1
  uniqueKeyspaces: true