graphName: "biochemical_network"
schema: "biochemical_network.gql"
scales:
  - 500
  - 1000
  - 2000
repeatsPerQuery: 5

queries: "queries_write.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true