graphName: "biochemical_network"
schema: "biochemical_network.gql"
queries: "queries.yml"
scales:
  - 500
  - 1000
  - 2000
repeatsPerQuery: 5

commitQueries: false
concurrency:
  clients: 1
  uniqueKeyspaces: true