graphName: "financial"
schema: "financial.gql"
scales:
  - 2000
  - 8000
  - 16000
  - 32000
repeatsPerQuery: 5

queries: "queries_write.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true