graphName: "financial"
schema: "financial.gql"
scales:
  - 2000
  - 4000
  - 8000
  - 16000
repeatsPerQuery: 5

queries: "queries_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true