graphName: "financial"
schema: "financial.gql"
scales:
  - 400
  - 1000
  - 2000
repeatsPerQuery: 5

queries: "queries_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true