graphName: "road_network"
schema: "road_network.gql"
queries: "queries.yml"
scales:
  - 2000
  - 6000
  - 10000
  - 14000

repeatsPerQuery: 5
  # TODO
  # concurrency:
  #   clients: 1
# mixed:
# replication: 1