graphName: "generic_uniform_network"
schema: "schema.gql"
scales:
  - 1000
  - 4000
  - 6000
  - 8000
  - 10000
  - 12000
repeatsPerQuery: 0

queries: "queries_complex_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true
