graphName: "generic_uniform_network"
schema: "schema.gql"
scales:
  - 200
  - 400
  - 600

repeatsPerQuery: 2

queries: "queries_complex_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true
