graphName: "generic_uniform_network"
schema: "schema.gql"
scales:
  - 2000
  - 8000
  - 16000
  - 32000

repeatsPerQuery: 3

queries: "queries_complex_write.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: true

concurrency:
  clients: 1
  uniqueKeyspaces: true