graphName: "biochem_network"
schema: "biochem_network.gql"
queries: "queries.yml"
scales:
  - 4000
  - 10000
  - 20000
repeatsPerQuery: 5
  # TODO
  # concurrency:
  #   clients: 1
# mixed:
# replication: 1