graphName: "road_network"
schema: "road_network.gql"

scales:
  - 400

repeatsPerQuery: 5

queries: "queries.yml"
deleteInsertedConcepts: true
traceDeletion: false

concurrency:
  clients: 1
  uniqueKeyspaces: true
