graphName: "road_network"
schema: "road_network.gql"
queries: "queries.yml"

scales:
  - 400

repeatsPerQuery: 5
  # TODO
  # concurrency:
  #   clients: 1
# mixed:
# replication: 1

commitQueries: true

concurrency:
  clients: 11
  uniqueKeyspaces: false
