graphName: "road_network"
schema: "road_network.gql"
scales:
- 400
- 1000
- 2000
#  - 14000

repeatsPerQuery: 5

queries: "queries_write.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true