graphName: "road_network"
schema: "road_network.gql"
queries: "queries.yml"
scales:
- 400
- 1000
- 2000
#  - 14000

repeatsPerQuery: 5

commitQueries: false
concurrency:
  clients: 1
  uniqueKeyspaces: true