graphName: "road_network"
schema: "road_network.gql"
scales:
- 2000
- 4000
- 8000
- 16000

repeatsPerQuery: 5

queries: "queries_write.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: true

concurrency:
  clients: 1
  uniqueKeyspaces: true