graphName: "road_network"
schema: "road_network.gql"
scales:
- 1000
- 2000
- 4000

repeatsPerQuery: 5

queries: "queries_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true