graphName: "road_network"
schema: "road_network.gql"
scales:
- 400
- 1000
- 2000
#  - 14000

repeatsPerQuery: 5

queries: "queries.yml"
deleteInsertedConcepts: true

concurrency:
  clients: 1
  uniqueKeyspaces: true