name: "Social Network - Read"
description: "Social network reads with: Increasing C_in, Constant R_out, Scaling A_out"
dataGenerator: "social_network"
schema: "social_network.gql"
scales:
  - 2000
  - 4000
  - 8000
repeatsPerQuery: 10

queries: "queries_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true