#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2019 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_build_tools//ci:run-bazel-rbe -- << parameters.command >>

jobs:
  build:
    machine: true
    working_directory: ~/benchmark
    steps:
      - checkout
      - install-bazel-linux-rbe
      - run-bazel-rbe:
          command: bazel build //...

  test:
    machine: true
    working_directory: ~/benchmark
    steps:
      - checkout
      - install-bazel-linux-rbe
      # run unit tests
      - run-bazel-rbe:
          command: bazel test //generator/test:data-generator-unit-tests --test_output=errors
      - run-bazel-rbe:
          command: bazel test //common/analysis/test:insert-query-analysis-unit-test --test_output=errors
      - run-bazel-rbe:
          command: bazel test //common/configuration/test:configuration-test --test_output=errors
      # run integration tests that do not depend on external grakn
#      - run-bazel-rbe:
#          command: bazel test //querygen/test-integration:query-generator-it --test_output=errors
      - run-bazel-rbe:
          command: bazel test //querygen/test-integration:query-sampler-it --test_output=errors
      - run-bazel-rbe:
          command: bazel test //querygen/test-integration:schema-walker-it --test_output=errors
      # run integration tests
      - run-bazel-rbe:
          command: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir dist && tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start
      - run: bazel test //profiler/test-integration:profiler-bootup-test-integration --test_output=errors
      - run: bazel test //profiler/test-integration:profiler-static-data-import-it --test_output=errors
      - run: bazel test //generator/test-integration:keyspace-schema-labels-it --test_output=errors


workflows:
  version: 2
  benchmark:
    jobs:
      - build
      - test
