name: "Taxfix small - read & write with commits"
description: "Small sample of taxfix queries without data generation"
dataGenerator: "taxfix"
schema: "taxfix_schema.gql"
repeatsPerQuery: 2

queries: "queries_small.yml"
deleteCommitedQueries: false
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true