name: "Taxfix - read & write with commits"
description: "Large sample of taxfix queries without data generation"
dataGenerator: "taxfix"
schema: "taxfix_schema.gql"
repeatsPerQuery: 1

queries: "queries_read.yml"
deleteInsertedConcepts: false
traceDeleteInsertedConcepts: false

concurrency:
  clients: 2
  uniqueKeyspaces: true
