graphName: "taxfix"
schema: "taxfix_schema.gql"
repeatsPerQuery: 1

queries: "queries.yml"
deleteInsertedConcepts: false
traceDeleteInsertedConcepts: false

concurrency:
  clients: 2
  uniqueKeyspaces: true
