graphName: "taxfix"
schema: "taxfix_schema.gql"
repeatsPerQuery: 2

queries: "queries_small.yml"
deleteCommitedQueries: false
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: true