name: "Road Network - Read"
description: "Road network reads with: Constant C_in, Constant R_out, Constant A_out"
dataGenerator: "road_network"
schema: "road_network.gql"
scales:
  - 1000
  - 4000
  - 8000

repeatsPerQuery: 50

queries: "queries_read.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: false

concurrency:
  clients: 4
  uniqueKeyspaces: false