name: "Road Network - Write"
description: "Road network writes with: Constant C_in, Constant R_out, Constant A_out"
dataGenerator: "road_network"
schema: "road_network.gql"
scales:
  - 2000
  - 4000
  - 8000

repeatsPerQuery: 5

queries: "queries_write.yml"
deleteInsertedConcepts: true
traceDeleteInsertedConcepts: true

concurrency:
  clients: 4
  uniqueKeyspaces: false