graphName: "social_network"
schema: "social_network.gql"
scales:
  - 400
  - 1000
  - 2000
repeatsPerQuery: 5

queries: "queries.yml"
deleteInsertedConcepts: true

concurrency:
  clients: 1
  uniqueKeyspaces: true